// packages/grid-react/src/DataGrid.tsx
import '@tipolox/litgrid-web'
import type {
  BestFitColumnWidth,
  ColumnReorderDetail,
  ColumnStateChangeDetail,
  ColumnVisibilityChangeDetail,
  DataGridElement,
  GridColumn,
  GridColumnState,
  GridConfig,
  GridFilter,
  GridPaginationState,
  GridSelection,
  GridTheme,
  SelectionIntent
} from '@tipolox/litgrid-web'
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef
} from 'react'
import { syncGridInputs } from './gridBindings.js'

export type DataGridProps = {
  data: unknown[]
  columns?: GridColumn[]
  config?: GridConfig
  theme?: GridTheme
  ariaLabel?: string
  ariaDescription?: string
  screenReaderAnnouncements?: boolean
  height?: number
  rowHeight?: number
  overscan?: number
  columnOverscan?: number
  bestFitSampleSize?: number
  quickSearchDebounceThreshold?: number
  quickSearchDebounceMs?: number
  columnStateStorageKey?: string
  onColumnStateChange?: (detail: ColumnStateChangeDetail) => void
  onColumnReorder?: (detail: ColumnReorderDetail) => void
  onColumnVisibilityChange?: (detail: ColumnVisibilityChangeDetail) => void
}

export type DataGridRef = {
  readonly gridElement: DataGridElement | null
  getRowHeight(rowIndex: number): number
  getColumnWidth(column: GridColumn): number
  setRowHeight(rowIndex: number, height: number): void
  resetRowHeight(rowIndex: number): void
  resetAllRowHeights(): void
  setColumnWidth(columnKey: string, width: number): void
  resetColumnWidth(columnKey: string): void
  resetAllColumnWidths(): void
  moveColumn(columnKey: string, targetIndex: number): void
  getColumnOrder(): string[]
  setColumnOrder(columnKeys: string[]): void
  resetColumnOrder(): void
  setColumnVisible(columnKey: string, visible: boolean): void
  isColumnVisible(columnKey: string): boolean
  getVisibleColumnKeys(): string[]
  resetColumnVisibility(): void
  getColumnState(): GridColumnState
  setColumnState(state: GridColumnState): void
  resetColumnState(): void
  bestFitColumn(columnKey: string): number | null
  bestFitAllColumns(): BestFitColumnWidth[]
  copySelectedCells(): Promise<boolean>
  copySelectedRows(): Promise<boolean>
  setQuickSearch(query: string): void
  clearQuickSearch(): void
  getQuickSearch(): string
  setFilter(filter: GridFilter): void
  clearFilter(columnKey?: string): void
  getFilters(): GridFilter[]
  setPage(pageIndex: number): void
  setPageSize(pageSize: number): void
  getPagination(): GridPaginationState
  getTotalRowCount(): number
  selectRow(rowIndex: number, intent?: SelectionIntent): void
  selectAllRows(): void
  clearSelection(): void
  getSelection(): GridSelection
  isRowSelected(rowIndex: number): boolean
  isCellSelected(rowIndex: number, columnKey: string): boolean
}

export type DataGridInstance = DataGridRef

const GRID_UNAVAILABLE_MESSAGE = 'LitGrid is not available before the React component is mounted.'

export const DataGrid = forwardRef<DataGridRef, DataGridProps>(function DataGrid(
  {
    data,
    columns = [],
    config = {},
    theme = 'light',
    ariaLabel = 'Data grid',
    ariaDescription = '',
    screenReaderAnnouncements = true,
    height = 320,
    rowHeight = 36,
    overscan = 4,
    columnOverscan = 2,
    bestFitSampleSize = 10,
    quickSearchDebounceThreshold = 10000,
    quickSearchDebounceMs = 150,
    columnStateStorageKey,
    onColumnStateChange,
    onColumnReorder,
    onColumnVisibilityChange
  },
  forwardedRef
) {
  const gridRef = useRef<DataGridElement | null>(null)

  const requireGridElement = (): DataGridElement => {
    if (!gridRef.current) throw new Error(GRID_UNAVAILABLE_MESSAGE)
    return gridRef.current
  }

  useImperativeHandle(
    forwardedRef,
    () => ({
      get gridElement() {
        return gridRef.current
      },
      getRowHeight: (rowIndex: number) => requireGridElement().getRowHeight(rowIndex),
      getColumnWidth: (column: GridColumn) => requireGridElement().getColumnWidth(column),
      setRowHeight: (rowIndex: number, heightVal: number) => requireGridElement().setRowHeight(rowIndex, heightVal),
      resetRowHeight: (rowIndex: number) => requireGridElement().resetRowHeight(rowIndex),
      resetAllRowHeights: () => requireGridElement().resetAllRowHeights(),
      setColumnWidth: (columnKey: string, width: number) => requireGridElement().setColumnWidth(columnKey, width),
      resetColumnWidth: (columnKey: string) => requireGridElement().resetColumnWidth(columnKey),
      resetAllColumnWidths: () => requireGridElement().resetAllColumnWidths(),
      moveColumn: (columnKey: string, targetIndex: number) => requireGridElement().moveColumn(columnKey, targetIndex),
      getColumnOrder: () => requireGridElement().getColumnOrder(),
      setColumnOrder: (columnKeys: string[]) => requireGridElement().setColumnOrder(columnKeys),
      resetColumnOrder: () => requireGridElement().resetColumnOrder(),
      setColumnVisible: (columnKey: string, visible: boolean) => requireGridElement().setColumnVisible(columnKey, visible),
      isColumnVisible: (columnKey: string) => requireGridElement().isColumnVisible(columnKey),
      getVisibleColumnKeys: () => requireGridElement().getVisibleColumnKeys(),
      resetColumnVisibility: () => requireGridElement().resetColumnVisibility(),
      getColumnState: () => requireGridElement().getColumnState(),
      setColumnState: (state: GridColumnState) => requireGridElement().setColumnState(state),
      resetColumnState: () => requireGridElement().resetColumnState(),
      bestFitColumn: (columnKey: string) => requireGridElement().bestFitColumn(columnKey),
      bestFitAllColumns: () => requireGridElement().bestFitAllColumns(),
      copySelectedCells: () => requireGridElement().copySelectedCells(),
      copySelectedRows: () => requireGridElement().copySelectedRows(),
      setQuickSearch: (query: string) => requireGridElement().setQuickSearch(query),
      clearQuickSearch: () => requireGridElement().clearQuickSearch(),
      getQuickSearch: () => requireGridElement().getQuickSearch(),
      setFilter: (filter: GridFilter) => requireGridElement().setFilter(filter),
      clearFilter: (columnKey?: string) => requireGridElement().clearFilter(columnKey),
      getFilters: () => requireGridElement().getFilters(),
      setPage: (pageIndex: number) => requireGridElement().setPage(pageIndex),
      setPageSize: (pageSize: number) => requireGridElement().setPageSize(pageSize),
      getPagination: () => requireGridElement().getPagination(),
      getTotalRowCount: () => requireGridElement().getTotalRowCount(),
      selectRow: (rowIndex: number, intent?: SelectionIntent) => requireGridElement().selectRow(rowIndex, intent),
      selectAllRows: () => requireGridElement().selectAllRows(),
      clearSelection: () => requireGridElement().clearSelection(),
      getSelection: () => requireGridElement().getSelection(),
      isRowSelected(rowIndex: number) {
        return requireGridElement().isRowSelected(rowIndex)
      },
      isCellSelected(rowIndex: number, columnKey: string) {
        return requireGridElement().isCellSelected(rowIndex, columnKey)
      }
    }),
    []
  )

  useEffect(() => {
    const grid = gridRef.current
    if (!grid) return

    syncGridInputs(grid, {
      data,
      columns,
      config,
      theme,
      ariaLabel,
      ariaDescription,
      screenReaderAnnouncements,
      height,
      rowHeight,
      overscan,
      columnOverscan,
      bestFitSampleSize,
      quickSearchDebounceThreshold,
      quickSearchDebounceMs,
      columnStateStorageKey
    })
  }, [
    data,
    columns,
    config,
    theme,
    ariaLabel,
    ariaDescription,
    screenReaderAnnouncements,
    height,
    rowHeight,
    overscan,
    columnOverscan,
    bestFitSampleSize,
    quickSearchDebounceThreshold,
    quickSearchDebounceMs,
    columnStateStorageKey
  ])

  useEffect(() => {
    const element = gridRef.current
    if (!element || !onColumnStateChange) return

    const handleColumnStateChange = (event: Event) => {
      onColumnStateChange((event as CustomEvent<ColumnStateChangeDetail>).detail)
    }

    element.addEventListener('column-state-change', handleColumnStateChange)
    return () => element.removeEventListener('column-state-change', handleColumnStateChange)
  }, [onColumnStateChange])

  useEffect(() => {
    const element = gridRef.current
    if (!element || !onColumnReorder) return

    const handleColumnReorder = (event: Event) => {
      onColumnReorder((event as CustomEvent<ColumnReorderDetail>).detail)
    }

    element.addEventListener('column-reorder', handleColumnReorder)
    return () => element.removeEventListener('column-reorder', handleColumnReorder)
  }, [onColumnReorder])

  useEffect(() => {
    const element = gridRef.current
    if (!element || !onColumnVisibilityChange) return

    const handleColumnVisibilityChange = (event: Event) => {
      onColumnVisibilityChange((event as CustomEvent<ColumnVisibilityChangeDetail>).detail)
    }

    element.addEventListener('column-visibility-change', handleColumnVisibilityChange)
    return () => element.removeEventListener('column-visibility-change', handleColumnVisibilityChange)
  }, [onColumnVisibilityChange])

  return <yc-grid ref={gridRef}></yc-grid>
})

// packages/grid-angular/src/DataGridComponent.ts
import '@tipolox/litgrid-web'
import {
  AfterViewInit,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild
} from '@angular/core'
import type {
  BestFitColumnWidth,
  ColumnReorderDetail,
  ColumnStateChangeDetail,
  ColumnVisibilityChangeDetail,
  DataGridElement,
  GridColumn,
  GridColumnState,
  GridConfig,
  GridFilter,
  GridPaginationState,
  GridSelection,
  GridTheme,
  SelectionIntent
} from '@tipolox/litgrid-web'
import { syncGridInputs } from './gridBindings'

@Component({
  selector: 'litgrid-data-grid',
  standalone: true,
  template: `
    <yc-grid
      #grid
      (column-state-change)="handleColumnStateChange($event)"
      (column-reorder)="handleColumnReorder($event)"
      (column-visibility-change)="handleColumnVisibilityChange($event)"
    ></yc-grid>
  `,
  styles: `
    :host {
      display: block;
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class DataGridComponent implements AfterViewInit, OnChanges {
  @Input() data: unknown[] = []
  @Input() columns: GridColumn[] = []
  @Input() config: GridConfig = {}
  @Input() theme: GridTheme = 'light'
  @Input() ariaLabel = 'Data grid'
  @Input() ariaDescription = ''
  @Input() screenReaderAnnouncements = true
  @Input() height = 320
  @Input() rowHeight = 36
  @Input() overscan = 4
  @Input() columnOverscan = 2
  @Input() bestFitSampleSize = 10
  @Input() quickSearchDebounceThreshold = 10_000
  @Input() quickSearchDebounceMs = 150
  @Input() columnStateStorageKey?: string

  @Output() readonly columnStateChange = new EventEmitter<ColumnStateChangeDetail>()
  @Output() readonly columnReorder = new EventEmitter<ColumnReorderDetail>()
  @Output() readonly columnVisibilityChange = new EventEmitter<ColumnVisibilityChangeDetail>()

  @ViewChild('grid', { static: true }) private gridRef?: ElementRef<DataGridElement>

  get gridElement(): DataGridElement | null {
    return this.gridRef?.nativeElement ?? null
  }

  ngAfterViewInit(): void {
    this.syncInputs()
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.syncInputs()
  }

  handleColumnStateChange(event: Event): void {
    this.columnStateChange.emit((event as CustomEvent<ColumnStateChangeDetail>).detail)
  }

  handleColumnReorder(event: Event): void {
    this.columnReorder.emit((event as CustomEvent<ColumnReorderDetail>).detail)
  }

  handleColumnVisibilityChange(event: Event): void {
    this.columnVisibilityChange.emit(
      (event as CustomEvent<ColumnVisibilityChangeDetail>).detail
    )
  }

  getRowHeight(rowIndex: number): number {
    return this.requireGridElement().getRowHeight(rowIndex)
  }

  getColumnWidth(column: GridColumn): number {
    return this.requireGridElement().getColumnWidth(column)
  }

  setRowHeight(rowIndex: number, height: number): void {
    this.requireGridElement().setRowHeight(rowIndex, height)
  }

  resetRowHeight(rowIndex: number): void {
    this.requireGridElement().resetRowHeight(rowIndex)
  }

  resetAllRowHeights(): void {
    this.requireGridElement().resetAllRowHeights()
  }

  setColumnWidth(columnKey: string, width: number): void {
    this.requireGridElement().setColumnWidth(columnKey, width)
  }

  resetColumnWidth(columnKey: string): void {
    this.requireGridElement().resetColumnWidth(columnKey)
  }

  resetAllColumnWidths(): void {
    this.requireGridElement().resetAllColumnWidths()
  }

  moveColumn(columnKey: string, targetIndex: number): void {
    this.requireGridElement().moveColumn(columnKey, targetIndex)
  }

  getColumnOrder(): string[] {
    return this.requireGridElement().getColumnOrder()
  }

  setColumnOrder(columnKeys: string[]): void {
    this.requireGridElement().setColumnOrder(columnKeys)
  }

  resetColumnOrder(): void {
    this.requireGridElement().resetColumnOrder()
  }

  setColumnVisible(columnKey: string, visible: boolean): void {
    this.requireGridElement().setColumnVisible(columnKey, visible)
  }

  isColumnVisible(columnKey: string): boolean {
    return this.requireGridElement().isColumnVisible(columnKey)
  }

  getVisibleColumnKeys(): string[] {
    return this.requireGridElement().getVisibleColumnKeys()
  }

  resetColumnVisibility(): void {
    this.requireGridElement().resetColumnVisibility()
  }

  getColumnState(): GridColumnState {
    return this.requireGridElement().getColumnState()
  }

  setColumnState(state: GridColumnState): void {
    this.requireGridElement().setColumnState(state)
  }

  resetColumnState(): void {
    this.requireGridElement().resetColumnState()
  }

  bestFitColumn(columnKey: string): number | null {
    return this.requireGridElement().bestFitColumn(columnKey)
  }

  bestFitAllColumns(): BestFitColumnWidth[] {
    return this.requireGridElement().bestFitAllColumns()
  }

  copySelectedCells(): Promise<boolean> {
    return this.requireGridElement().copySelectedCells()
  }

  copySelectedRows(): Promise<boolean> {
    return this.requireGridElement().copySelectedRows()
  }

  setQuickSearch(query: string): void {
    this.requireGridElement().setQuickSearch(query)
  }

  clearQuickSearch(): void {
    this.requireGridElement().clearQuickSearch()
  }

  getQuickSearch(): string {
    return this.requireGridElement().getQuickSearch()
  }

  setFilter(filter: GridFilter): void {
    this.requireGridElement().setFilter(filter)
  }

  clearFilter(columnKey?: string): void {
    this.requireGridElement().clearFilter(columnKey)
  }

  getFilters(): GridFilter[] {
    return this.requireGridElement().getFilters()
  }

  setPage(pageIndex: number): void {
    this.requireGridElement().setPage(pageIndex)
  }

  setPageSize(pageSize: number): void {
    this.requireGridElement().setPageSize(pageSize)
  }

  getPagination(): GridPaginationState {
    return this.requireGridElement().getPagination()
  }

  getTotalRowCount(): number {
    return this.requireGridElement().getTotalRowCount()
  }

  selectRow(rowIndex: number, intent?: SelectionIntent): void {
    this.requireGridElement().selectRow(rowIndex, intent)
  }

  selectAllRows(): void {
    this.requireGridElement().selectAllRows()
  }

  clearSelection(): void {
    this.requireGridElement().clearSelection()
  }

  getSelection(): GridSelection {
    return this.requireGridElement().getSelection()
  }

  isRowSelected(rowIndex: number): boolean {
    return this.requireGridElement().isRowSelected(rowIndex)
  }

  isCellSelected(rowIndex: number, columnKey: string): boolean {
    return this.requireGridElement().isCellSelected(rowIndex, columnKey)
  }

  private syncInputs(): void {
    const grid = this.gridElement
    if (!grid) return

    syncGridInputs(grid, this)
  }

  private requireGridElement(): DataGridElement {
    const grid = this.gridElement
    if (!grid) {
      throw new Error('LitGrid is not available before the Angular view is initialized.')
    }
    return grid
  }
}
